version: "3.2"
services:

  sql-server-db:
    container_name: friendly_brattain
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Abc@1234"
      ACCEPT_EULA: "Y"
  my-web-app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - sql-server-db